// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivgvgvhhkdcjozayahcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2Z3Zndmhoa2Rjam96YXlhaGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDg1MzIsImV4cCI6MjA3NDYyNDUzMn0.VXsy7w43KcT-bf9r5F3LLnoOjlBRmOggQBR96MQi_YY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});